[aws]
access_key_id     = "AAAxxxxxxxxxxxx"
secret_access_key = "SECRETxxxxxxxxx"
region            = "ap-northeast-1"

[step_functions]
arn = "arn:aws:states:ap-northeast-1:000000000000:stateMachine:test"
